# Generated by Django 5.0.1 on 2024-01-18 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('authorization_flag', models.BooleanField(default=False)),
                ('puzzle_requested', models.IntegerField(default=0)),
                ('solution_count', models.IntegerField(default=0)),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
