# Generated by Django 5.0.1 on 2024-01-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eVDR_api', '0003_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eVDR_api.chat')),
                ('latest_puzzle_solved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eVDR_api.indizi')),
            ],
        ),
    ]
