# Generated by Django 5.0.1 on 2024-01-29 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eVDR_api', '0005_alter_userstats_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
